name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        sudo apt -qq update
        sudo apt install --no-install-recommends -y \
          binfmt-support \
          qemu \
          qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: npm install, build
      run: |
        docker run --rm -t -v $PWD:/build mozillaiot/toolchain-linux-arm-node-8 bash -c "cd /build; ./package.sh"
